### ISSUE TITLE
Could not find Liga font / EnvironmentError: Open failed

### ISSUE THREAD

**Issue by amaisano** [ToxicFrog/Ligaturizer#48]
Every time - both with the manual and auto approach. I've copied the Liga font files as the code expects them to be named into every directory but still no dice. Nothing ever appears in output:

```
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 09:31 UTC 21-Mar-2018-D.
 Based on source from git with hash:
The following table(s) in the font have been ignored by FontForge
  Ignoring 'LTSH' linear threshold table
  Ignoring 'VDMX' vertical device metrics table
  Ignoring 'hdmx' horizontal device metrics table
The glyph named Omega is mapped to U+03A9.
But its name indicates it should be mapped to U+2126.
Ligaturizing font MesloLGMDZ-Regular.ttf (Meslo LG M DZ) as 'Liga Ligaturized Meslo'
    ...using ligatures from fonts/fira/distr/otf/FiraCode-Regular.otf
The requested file, FiraCode-Regular.otf, does not exist
Traceback (most recent call last):
  File "ligaturize.py", line 332, in <module>
    main()
  File "ligaturize.py", line 329, in main
    ligaturize_font(**vars(parse_args()))
  File "ligaturize.py", line 270, in ligaturize_font
    firacode = fontforge.open(ligature_font_file)
EnvironmentError: Open failed
```

**Comment by ToxicFrog** [comment]
did you `git clone --recurse-submodules` like the README says? If not try `git submodule update --init` and try again.

**Comment by amaisano** [comment]
I had checked this option, which I *think* does the same thing:

![screen shot 2018-09-27 at 10 15 17 am](https://user-images.githubusercontent.com/688435/46152080-43706380-c23e-11e8-90c7-45dc9f16c456.png)

but I will try it manually from CLI and see what's up. Thanks.

**Comment by amaisano** [comment]
Ah! Working, but I had to do the following:

`git submodule sync`
`git reset --hard`
`git submodule foreach git reset --hard`

Submodules man. They'll mess you up.
