### ISSUE TITLE
Automatic "make" build doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by jcklpe** [ToxicFrog/Ligaturizer#64]
Looks like the issue is that FiraBold is not included in the repo as a submodule? Do I just need to clone it in?

```
┌─    ~/Ligaturizer                                                            master  v4    
└─➤ make      
fontforge -lang=py -script build.py 2>&1 \
| fgrep -v 'This contextual rule applies no lookups.' \
| fgrep -v 'Bad device table'
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 11:21 UTC 24-Sep-2017-ML-D.
 Based on source from git with hash: 
The glyph named Tcommaaccent is mapped to U+021A.
  But its name indicates it should be mapped to U+0162.
The glyph named Delta is mapped to U+0394.
  But its name indicates it should be mapped to U+2206.
The glyph named Omega is mapped to U+03A9.
  But its name indicates it should be mapped to U+2126.
The glyph named tcommaaccent is mapped to U+021B.
  But its name indicates it should be mapped to U+0163.
The glyph named mu is mapped to U+03BC.
  But its name indicates it should be mapped to U+00B5.
The requested file, FiraCode-Bold.otf, does not exist
Ligaturizing font Input-BoldItalic_(InputSans-BoldItalic).ttf (Input) as 'liga-input-sans'
    ...using ligatures from fonts/fira/distr/otf/FiraCode-Bold.otf
Traceback (most recent call last):
  File "build.py", line 83, in <module>
    scale_character_glyphs_threshold=SCALE_CHARACTER_GLYPHS_THRESHOLD)
  File "/home/david/Ligaturizer/ligaturize.py", line 276, in ligaturize_font
    firacode = fontforge.open(ligature_font_file)
EnvironmentError: Open failed

```

**Comment by jcklpe** [comment]
Oh whoops, nvm I have to do a git submodule init and then update. I'm new. Sorry!
