### ISSUE TITLE
TypeError: ord() expected a character, but string of length 9 found 

### ISSUE THREAD

**Issue by SeanSobey** [ToxicFrog/Ligaturizer#73]
I am using the [dockerized](https://github.com/Rfvgyhn/docker-ligaturizer) version to run the ligaturize the latest [Hack](https://sourcefoundry.org/hack/) font. I am getting this error:
```
Copyright (c) 2000-2019. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20190801
 Based on sources from 10:15 UTC  2-Sep-2019-ML-D-GDK3.
Your version of iconv does not support the "Mac Roman" encoding.
If this causes problems, reconfigure --without-iconv.The following table(s) in the font have been ignored by FontForge
    Ignoring 'DSIG' digital signature table
Ligaturizing font input (Hack) as 'Hack Ligaturized'
     ...using ligatures from fonts/fira/distr/otf/FiraCode-Regular.otf
Traceback (most recent call last): 
   File "ligaturize.py", line 336, in <module> 
   File "ligaturize.py", line 333, in main 
        ligaturize_font(**vars(parse_args())) 
   File "ligaturize.py", line 273, in ligaturize_font 
        creator.add_ligature(lig_spec['chars'], lig_spec['firacode_ligature_name']) 
   File "ligaturize.py", line 164, in add_ligature 
        self.font[ord(char)].glyphname = char
TypeError: ord() expected a character, but string of length 9 found     
```
[Here](https://github.com/Rfvgyhn/docker-ligaturizer/issues/1) is the issue on the dockerized fork, and what seems a [related issue](https://github.com/ToxicFrog/Ligaturizer/issues/40#issuecomment-416404692).

**Comment by fsvehla** [comment]
Can reproduce with Lekton
