### ISSUE TITLE
EnvironmentError: A lookup named lookup.1.0 already exists

### ISSUE THREAD

**Issue by sc-1123** [ToxicFrog/Ligaturizer#84]
I use WSL Ubuntu 18.04.2 LTS bionic, got this error:  
```  
Traceback (most recent call last):
  File "build.py", line 105, in <module>
    scale_character_glyphs_threshold=SCALE_CHARACTER_GLYPHS_THRESHOLD)
  File "/home/dell/Ligaturizer/ligaturize.py", line 275, in ligaturize_font
    creator.add_ligature(lig_spec['chars'], lig_spec['firacode_ligature_name'])
  File "/home/dell/Ligaturizer/ligaturize.py", line 158, in add_ligature
    self.font.addLookup(lookup_name(i), 'gsub_single', (), ())
EnvironmentError: A lookup named lookup.1.0 already exists  
```  
The font I tried to ligaturize is Droid Sans Mono Nerd Font Complete Windows Compatible.

**Comment by tarunzoot** [comment]
if you have added your font name to `renamed_font` then comment that, then this will work
