### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by skqlix** [ToxicFrog/Ligaturizer#93]
```
Copyright (c) 2000-2020. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20201107
 Based on sources from 2020-11-07 21:17 UTC-ML-TtfDb-D-GDK3.
 Based on source from git with hash: f8bbd68cb29e31eba3215894ae4124a8ecdc2033
The following table(s) in the font have been ignored by FontForge
  Ignoring 'STAT' style attributes table
Glyph bounding box data exceeds font bounding box data for GID 7
  Subsequent errors will not be reported.
Ligaturizing font font.ttf (Quicksand Medium) as 'Liga 'Discordia''
    ...using ligatures from fonts/fira/distr/otf/FiraCode-Medium.otf
Warning: Mac string is a subset of the Windows string in the 'name' table
  for the Family string in the English (US) language.
Warning: Mac and Windows entries in the 'name' table differ for the
  Styles (SubFamily) string in the language English (US)
  Mac String: Medium
  Windows String: Regular
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
    ...saving to ''fonts/output/'\Liga'Discordia'-Medium.ttf' (Liga 'Discordia' Medium)
Save Failed
Traceback (most recent call last):
  File "ligaturize.py", line 338, in <module>
    main()
  File "ligaturize.py", line 335, in main
    ligaturize_font(**vars(parse_args()))
  File "ligaturize.py", line 294, in ligaturize_font
    font.generate(output_font_file)
OSError: Font generation failed
E:\Git\font\Ligaturizer\Ligaturizer>make
fontforge -lang=py -script build.py 2>&1 \
| fgrep -v 'This contextual rule applies no lookups.' \
| fgrep -v 'Bad device table'
'fgrep' is not recognized as an internal or external command,
operable program or batch file.
make: *** [Makefile:5: all] Error 255

E:\Git\font\Ligaturizer\Ligaturizer>fontforge -lang py -script ligaturize.py fonts/font.ttf --output-dir='fonts/output/' --output-name='Discordia'
Copyright (c) 2000-2020. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20201107
 Based on sources from 2020-11-07 21:17 UTC-ML-TtfDb-D-GDK3.
 Based on source from git with hash: f8bbd68cb29e31eba3215894ae4124a8ecdc2033
The following table(s) in the font have been ignored by FontForge
  Ignoring 'STAT' style attributes table
Glyph bounding box data exceeds font bounding box data for GID 7
  Subsequent errors will not be reported.
Ligaturizing font font.ttf (Quicksand Medium) as 'Liga 'Discordia''
    ...using ligatures from fonts/fira/distr/otf/FiraCode-Medium.otf
Warning: Mac string is a subset of the Windows string in the 'name' table
  for the Family string in the English (US) language.
Warning: Mac and Windows entries in the 'name' table differ for the
  Styles (SubFamily) string in the language English (US)
  Mac String: Medium
  Windows String: Regular
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
This contextual rule applies no lookups.
    ...saving to ''fonts/output/'\Liga'Discordia'-Medium.ttf' (Liga 'Discordia' Medium)
Save Failed
Traceback (most recent call last):
  File "ligaturize.py", line 338, in <module>
    main()
  File "ligaturize.py", line 335, in main
    ligaturize_font(**vars(parse_args()))
  File "ligaturize.py", line 294, in ligaturize_font
    font.generate(output_font_file)
OSError: Font generation failed
```

dunno why

**Comment by HansPinckaers** [comment]
I had this problem too, exporting to another folder worked for me.

**Comment by ToxicFrog** [comment]
I don't have a windows setup handy to test this on, so I'm leaving this open in case other people have insights but can't directly debug it myself.

**Comment by ThatXliner** [comment]
So basically, you need the `output` folder to exist

**Comment by KTibow** [comment]
I'm getting a `OSError: Open failed`
Full log:
```
The glyph named Omega is mapped to U+03A9.
But its name indicates it should be mapped to U+2126.
The glyph named slash is mapped to U+E216.
But its name indicates it should be mapped to U+002F.
The glyph named heart is mapped to U+F004.
But its name indicates it should be mapped to U+2665.
The glyph named home is mapped to U+F015.
But its name indicates it should be mapped to U+21B8.
The glyph named check is mapped to U+F046.
But its name indicates it should be mapped to U+2713.
The glyph named bell is mapped to U+F0A2.
But its name indicates it should be mapped to U+2407.
The glyph named circle is mapped to U+F111.
But its name indicates it should be mapped to U+25CB.
The glyph named smile is mapped to U+F118.
But its name indicates it should be mapped to U+263A.
The glyph named frown is mapped to U+F119.
But its name indicates it should be mapped to U+2322.
The glyph named bullseye is mapped to U+F140.
But its name indicates it should be mapped to U+25CE.
The glyph named compass is mapped to U+F14E.
But its name indicates it should be mapped to U+263C.
The glyph named female is mapped to U+F182.
But its name indicates it should be mapped to U+2640.
The glyph named male is mapped to U+F183.
But its name indicates it should be mapped to U+2642.
The glyph named sun is mapped to U+F185.
But its name indicates it should be mapped to U+263C.
The glyph named venus is mapped to U+F221.
But its name indicates it should be mapped to U+2640.
The glyph named question is mapped to U+F420.
But its name indicates it should be mapped to U+003F.
The glyph named check is mapped to U+F42E.
But its name indicates it should be mapped to U+2713.
The glyph named x is mapped to U+F467.
But its name indicates it should be mapped to U+0078.
The glyph named home is mapped to U+F46D.
But its name indicates it should be mapped to U+21B8.
The glyph named ellipsis is mapped to U+F475.
But its name indicates it should be mapped to U+2026.
The glyph named bell is mapped to U+F49A.
But its name indicates it should be mapped to U+2407.
The glyph named alpha is mapped to U+F52A.
But its name indicates it should be mapped to U+03B1.
The glyph named at is mapped to U+F564.
But its name indicates it should be mapped to U+0040.
The glyph named backspace is mapped to U+F56D.
But its name indicates it should be mapped to U+2408.
The glyph named bell is mapped to U+F599.
But its name indicates it should be mapped to U+2407.
The glyph named beta is mapped to U+F5A0.
But its name indicates it should be mapped to U+03B2.
The glyph named box is mapped to U+F5D3.
But its name indicates it should be mapped to U+25A1.
The glyph named check is mapped to U+F62B.
But its name indicates it should be mapped to U+2713.
The glyph named compass is mapped to U+F68A.
But its name indicates it should be mapped to U+263C.
The glyph named delete is mapped to U+F6BF.
But its name indicates it should be mapped to U+2421.
The glyph named delta is mapped to U+F6C1.
But its name indicates it should be mapped to U+03B4.
The glyph named diamond is mapped to U+F6C7.
But its name indicates it should be mapped to U+2666.
The glyph named earth is mapped to U+F6E6.
But its name indicates it should be mapped to U+2641.
The glyph named equal is mapped to U+F6FB.
But its name indicates it should be mapped to U+003D.
The glyph named heart is mapped to U+F7D0.
But its name indicates it should be mapped to U+2665.
The glyph named home is mapped to U+F7DB.
But its name indicates it should be mapped to U+21B8.
The glyph named image is mapped to U+F7E8.
But its name indicates it should be mapped to U+22B7.
The glyph named minus is mapped to U+F873.
But its name indicates it should be mapped to U+2212.
The glyph named omega is mapped to U+F8C8.
But its name indicates it should be mapped to U+03C9.
The glyph named percent is mapped to U+F8EF.
But its name indicates it should be mapped to U+0025.
The glyph named pi is mapped to U+F8FE.
But its name indicates it should be mapped to U+03C0.
The glyph named plus is mapped to U+F914.
But its name indicates it should be mapped to U+002B.
The glyph named sigma is mapped to U+F99F.
But its name indicates it should be mapped to U+03C3.
The glyph named tie is mapped to U+FA18.
But its name indicates it should be mapped to U+2040.
The glyph named triangle is mapped to U+FA35.
But its name indicates it should be mapped to U+25B3.
The glyph named bullseye is mapped to U+FADC.
But its name indicates it should be mapped to U+25CE.
The glyph named copyright is mapped to U+FAE5.
But its name indicates it should be mapped to U+00A9.
The glyph named lambda is mapped to U+FB26.
But its name indicates it should be mapped to U+03BB.
The glyph named gradient is mapped to U+FB9E.
But its name indicates it should be mapped to U+2207.
The glyph named asterisk is mapped to U+FBC2.
But its name indicates it should be mapped to U+002A.
The glyph named hook is mapped to U+FBE0.
But its name indicates it should be mapped to U+2440.
The glyph named infinity is mapped to U+FBE2.
But its name indicates it should be mapped to U+221E.
The glyph named prescription is mapped to U+FC04.
But its name indicates it should be mapped to U+211E.
The glyph named tilde is mapped to U+FC23.
But its name indicates it should be mapped to U+02DC.
The glyph named cancel is mapped to U+FC38.
But its name indicates it should be mapped to U+2418.
The glyph named square is mapped to U+FC62.
But its name indicates it should be mapped to U+25A1.
The glyph named circle is mapped to U+FC63.
But its name indicates it should be mapped to U+25CB.
The glyph named null is mapped to U+FCE0.
But its name indicates it should be mapped to U+2400.
The glyph named pipe is mapped to U+FCE3.
But its name indicates it should be mapped to U+01C0.
The glyph named ring is mapped to U+FCE9.
But its name indicates it should be mapped to U+02DA.
Ligaturizing font Ubuntu Bold Nerd Font Complete.ttf (Ubuntu Nerd Font) as 'Liga Ubuntu Nerd Font'
    ...using ligatures from fonts/fira/distr/otf/FiraCode-Bold.otf
The requested file, FiraCode-Bold.otf, does not exist
Traceback (most recent call last):
  File "/home/kendell/Ligaturizer/build.py", line 92, in <module>
    ligaturize_font(
  File "/home/kendell/Ligaturizer/ligaturize.py", line 267, in ligaturize_font
    firacode = fontforge.open(ligature_font_file)
OSError: Open failed
```

**Comment by asterized** [comment]
> I'm getting a `OSError: Open failed` Full log:
> 
> ```
> The glyph named Omega is mapped to U+03A9.
> But its name indicates it should be mapped to U+2126.
> The glyph named slash is mapped to U+E216.
> But its name indicates it should be mapped to U+002F.
> The glyph named heart is mapped to U+F004.
> But its name indicates it should be mapped to U+2665.
> The glyph named home is mapped to U+F015.
> But its name indicates it should be mapped to U+21B8.
> The glyph named check is mapped to U+F046.
> But its name indicates it should be mapped to U+2713.
> The glyph named bell is mapped to U+F0A2.
> But its name indicates it should be mapped to U+2407.
> The glyph named circle is mapped to U+F111.
> But its name indicates it should be mapped to U+25CB.
> The glyph named smile is mapped to U+F118.
> But its name indicates it should be mapped to U+263A.
> The glyph named frown is mapped to U+F119.
> But its name indicates it should be mapped to U+2322.
> The glyph named bullseye is mapped to U+F140.
> But its name indicates it should be mapped to U+25CE.
> The glyph named compass is mapped to U+F14E.
> But its name indicates it should be mapped to U+263C.
> The glyph named female is mapped to U+F182.
> But its name indicates it should be mapped to U+2640.
> The glyph named male is mapped to U+F183.
> But its name indicates it should be mapped to U+2642.
> The glyph named sun is mapped to U+F185.
> But its name indicates it should be mapped to U+263C.
> The glyph named venus is mapped to U+F221.
> But its name indicates it should be mapped to U+2640.
> The glyph named question is mapped to U+F420.
> But its name indicates it should be mapped to U+003F.
> The glyph named check is mapped to U+F42E.
> But its name indicates it should be mapped to U+2713.
> The glyph named x is mapped to U+F467.
> But its name indicates it should be mapped to U+0078.
> The glyph named home is mapped to U+F46D.
> But its name indicates it should be mapped to U+21B8.
> The glyph named ellipsis is mapped to U+F475.
> But its name indicates it should be mapped to U+2026.
> The glyph named bell is mapped to U+F49A.
> But its name indicates it should be mapped to U+2407.
> The glyph named alpha is mapped to U+F52A.
> But its name indicates it should be mapped to U+03B1.
> The glyph named at is mapped to U+F564.
> But its name indicates it should be mapped to U+0040.
> The glyph named backspace is mapped to U+F56D.
> But its name indicates it should be mapped to U+2408.
> The glyph named bell is mapped to U+F599.
> But its name indicates it should be mapped to U+2407.
> The glyph named beta is mapped to U+F5A0.
> But its name indicates it should be mapped to U+03B2.
> The glyph named box is mapped to U+F5D3.
> But its name indicates it should be mapped to U+25A1.
> The glyph named check is mapped to U+F62B.
> But its name indicates it should be mapped to U+2713.
> The glyph named compass is mapped to U+F68A.
> But its name indicates it should be mapped to U+263C.
> The glyph named delete is mapped to U+F6BF.
> But its name indicates it should be mapped to U+2421.
> The glyph named delta is mapped to U+F6C1.
> But its name indicates it should be mapped to U+03B4.
> The glyph named diamond is mapped to U+F6C7.
> But its name indicates it should be mapped to U+2666.
> The glyph named earth is mapped to U+F6E6.
> But its name indicates it should be mapped to U+2641.
> The glyph named equal is mapped to U+F6FB.
> But its name indicates it should be mapped to U+003D.
> The glyph named heart is mapped to U+F7D0.
> But its name indicates it should be mapped to U+2665.
> The glyph named home is mapped to U+F7DB.
> But its name indicates it should be mapped to U+21B8.
> The glyph named image is mapped to U+F7E8.
> But its name indicates it should be mapped to U+22B7.
> The glyph named minus is mapped to U+F873.
> But its name indicates it should be mapped to U+2212.
> The glyph named omega is mapped to U+F8C8.
> But its name indicates it should be mapped to U+03C9.
> The glyph named percent is mapped to U+F8EF.
> But its name indicates it should be mapped to U+0025.
> The glyph named pi is mapped to U+F8FE.
> But its name indicates it should be mapped to U+03C0.
> The glyph named plus is mapped to U+F914.
> But its name indicates it should be mapped to U+002B.
> The glyph named sigma is mapped to U+F99F.
> But its name indicates it should be mapped to U+03C3.
> The glyph named tie is mapped to U+FA18.
> But its name indicates it should be mapped to U+2040.
> The glyph named triangle is mapped to U+FA35.
> But its name indicates it should be mapped to U+25B3.
> The glyph named bullseye is mapped to U+FADC.
> But its name indicates it should be mapped to U+25CE.
> The glyph named copyright is mapped to U+FAE5.
> But its name indicates it should be mapped to U+00A9.
> The glyph named lambda is mapped to U+FB26.
> But its name indicates it should be mapped to U+03BB.
> The glyph named gradient is mapped to U+FB9E.
> But its name indicates it should be mapped to U+2207.
> The glyph named asterisk is mapped to U+FBC2.
> But its name indicates it should be mapped to U+002A.
> The glyph named hook is mapped to U+FBE0.
> But its name indicates it should be mapped to U+2440.
> The glyph named infinity is mapped to U+FBE2.
> But its name indicates it should be mapped to U+221E.
> The glyph named prescription is mapped to U+FC04.
> But its name indicates it should be mapped to U+211E.
> The glyph named tilde is mapped to U+FC23.
> But its name indicates it should be mapped to U+02DC.
> The glyph named cancel is mapped to U+FC38.
> But its name indicates it should be mapped to U+2418.
> The glyph named square is mapped to U+FC62.
> But its name indicates it should be mapped to U+25A1.
> The glyph named circle is mapped to U+FC63.
> But its name indicates it should be mapped to U+25CB.
> The glyph named null is mapped to U+FCE0.
> But its name indicates it should be mapped to U+2400.
> The glyph named pipe is mapped to U+FCE3.
> But its name indicates it should be mapped to U+01C0.
> The glyph named ring is mapped to U+FCE9.
> But its name indicates it should be mapped to U+02DA.
> Ligaturizing font Ubuntu Bold Nerd Font Complete.ttf (Ubuntu Nerd Font) as 'Liga Ubuntu Nerd Font'
>     ...using ligatures from fonts/fira/distr/otf/FiraCode-Bold.otf
> The requested file, FiraCode-Bold.otf, does not exist
> Traceback (most recent call last):
>   File "/home/kendell/Ligaturizer/build.py", line 92, in <module>
>     ligaturize_font(
>   File "/home/kendell/Ligaturizer/ligaturize.py", line 267, in ligaturize_font
>     firacode = fontforge.open(ligature_font_file)
> OSError: Open failed
> ```

extract the zip from the fira code repo into the fonts folder and rename it to fira
https://github.com/tonsky/FiraCode/tree/e9943d2d631a4558613d7a77c58ed1d3cb790992

**Comment by svonjoi** [comment]
`--output-dir=/home/user/folder/`
instead of
`--output-dir=~/folder/`
worked for me
